main: at.srsyntax.tabstatistic.TabStatistic
name: TabStatistic
version: ${version}
api-version: 1.19

softdepend: [PlaceholderAPI]

author: SrSyntaxAT
website: https://srsyntax.at/

commands:
  modifystatistic:
    description: Modify the statistics of a player.
    aliases:
      - modifystats